name: Deploy to Alwaysdata

on:
  push:
    branches:
      - main  # ou master si ton repo utilise ce nom

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.A2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ssh-mspr2backend.alwaysdata.net >> ~/.ssh/known_hosts

      - name: Cleanup SSH agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -D  # Supprime toutes les clés chargées précédemment
          ssh-add ~/.ssh/id_rsa  # Ajoute la clé spécifiée

      - name: Deploy via rsync
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes" ./ mspr2backend@ssh-mspr2backend.alwaysdata.net:~/www/
