name: Deploy to Alwaysdata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.A2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ssh-mspr2backend.alwaysdata.net >> ~/.ssh/known_hosts
          echo "Host alwaysdata
            HostName ssh-mspr2backend.alwaysdata.net
            User mspr2backend
            IdentityFile ~/.ssh/id_rsa
            IdentitiesOnly yes
          " >> ~/.ssh/config

      - name: Deploy via rsync
        run: |
          rsync -avz --delete ./ alwaysdata:~/backend
